from PySide6.QtWidgets import QVBoxLayout, QWidget, QLabel, QSizePolicy
from MotionTree import MotionTree


class HelpPage(QWidget):
    def __init__(self):
        super().__init__()
        self.layout = QVBoxLayout()
        # self.setSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        label_1 = QLabel("User Manual:")
        self.layout.addWidget(label_1)
        self.labels = [
            "1. Use the sliders to change the parameters used for building the Motion Tree.",
            "2. The path to the input and output directories have been set but can be changed if needed.",
            "3. The input directories should be separated into 2 different folders: one for standard PDB files, and the \n"
            "   other for PDB files generated by DynDom. The same goes for output directories. ",
            "4. For the Standard page, put in the 4-character codes of the 2 proteins and their respective 1-letter chain\n"
            "   code that you wish to build a Motion Tree from.",
            "5. For the DynDom page, use the code of the PDB file given by the DynDom output. Only store the PDB files\n"
            "   into the input directory and not the zip folder.",
            "6. If the 4-character code PDB file is not found, the application will use file transfer protocols to get it\n"
            "   from the PDB database. This does not apply to the DynDom PDB files.",
            "7. Multiple Motion Trees can be build at the same time. Just put in a new set, press build again, and a new\n"
            "   window will pop up.",
            "8. The output window will show the distance difference matrix and Motion Tree dendrogram. Click on the buttons\n"
            "   to change the image",
            "9. Once a Motion Tree is successfully built, a folder will be created that holds the outputs. For Standard,\n"
            "   it will create a folder with the naming scheme: protein1_chain1_protein2_chain2. \n"
            "   For DynDom, it follows the code of the PDB file",
            "10.To see areas involved in the structural changes of the protein for each effective node, open the PML\n"
            "   files located in the created folder.",
            "11.These is a .info text file that shows the residues in each node."
        ]

        for label in self.labels:
            widget = QLabel(label)
            widget.setContentsMargins(0, 0, 0, 0)
            self.layout.addWidget(widget)

        self.setLayout(self.layout)


